# Generated by Django 2.2.3 on 2019-07-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0002_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
