# Generated by Django 2.2.3 on 2019-07-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0003_bus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdata.Bus')),
            ],
        ),
    ]
