# Generated by Django 2.2.3 on 2019-07-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0004_busloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busloc',
            name='bus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bdata.Bus'),
        ),
    ]
