# Generated by Django 2.2.3 on 2019-08-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0005_auto_20190724_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=3)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdata.Route')),
            ],
        ),
    ]
