# Generated by Django 2.2.3 on 2019-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0006_bpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpoint',
            name='route',
        ),
        migrations.AddField(
            model_name='bpoint',
            name='route',
            field=models.ManyToManyField(to='bdata.Route'),
        ),
    ]
