# Generated by Django 2.2.3 on 2019-08-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdata', '0009_auto_20190802_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpoint',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bpoint',
            name='long',
            field=models.FloatField(default=0.0),
        ),
    ]
